In [2]:
import numpy as np
import matplotlib.pyplot as plt
import cmath

#1)

##b)

In [3]:
I = np.identity(4)
O = np.zeros((4, 4))
y = np.array([1, 0, 0, 0])
x = np.transpose(y)
o = np.zeros((1, 4))

In [4]:
A = np.array([
    [x, I, I, y],
    [x, I, I, y],
    [o, I, O, y]
])

<ipython-input-4-96e0c5045c4c>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  A = np.array([

In [5]:
c1= np.dot(np.dot(np.dot(A[0,0], A[2,1]), A[1,2]), A[0,3])
c2= np.dot(np.dot(np.dot(A[1,0], A[2,1]), A[0,2]), A[0,3])
c3= np.dot(np.dot(np.dot(A[0,0], A[1,1]), A[0,2]), A[2,3])
c4= np.dot(np.dot(np.dot(A[1,0], A[0,1]), A[0,2]), A[1,3])

##c)

In [6]:
N= c1**2 + c2**2+ c3**2+ c4**2
N

4.0

##d)

In [7]:
y_N= (1/np.sqrt(N))*y

In [8]:
A_N = np.array([
    [x, I, I, y_N],
    [x, I, I, y_N],
    [o, I, O, y_N]
])

<ipython-input-8-09f55e306f6c>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  A_N = np.array([

In [9]:
c1N= np.dot(np.dot(np.dot(A_N[0,0], A_N[2,1]), A_N[1,2]), A_N[0,3])
c2N= np.dot(np.dot(np.dot(A_N[1,0], A_N[2,1]), A_N[0,2]), A_N[0,3])
c3N= np.dot(np.dot(np.dot(A_N[0,0], A_N[1,1]), A_N[0,2]), A_N[2,3])
c4N= np.dot(np.dot(np.dot(A_N[1,0], A_N[0,1]), A_N[0,2]), A_N[1,3])

In [10]:
N= c1N**2 + c2N**2+ c3N**2+ c4N**2
N

1.0